version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  
  bot:
    image: telegram_bot:latest
    container_name: telegram_bot
    environment:
      - "REDIS_URL=redis://redis:6379/0"
    depends_on:
      - redis
    ports:
      - "8000:8000"
