version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  
  bot:
    image: telegram_bot:latest
    container_name: telegram_bot
    environment:
      - "BOT_TOKEN=${BOT_TOKEN}"
      - "REDIS_URL=${REDIS_URL}"
    depends_on:
      - redis
    ports:
      - "8000:8000"
